services:
  employee-service:
    build:
      context: .
      dockerfile: ./EmployeeService/Dockerfile
    ports:
      - "8080:8080"  
    environment:
      - ASPNETCORE_URLS=http://+:8080 
      - ConnectionStrings__DefaultConnection=Server=mysql;Database=EmployeeDB;Uid=root;Pwd=my-secret-pw;
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: EmployeeDB
    ports:
      - "3307:3307"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  mysql_data: